# Generated by Django 4.1.1 on 2023-09-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="created_at",
        ),
    ]
