# Generated by Django 4.1.1 on 2023-09-14 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0002_remove_person_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
